# MUSIC GENRE CLASSIFICATION 

This venture was done on Google Colab Notebook "https://colab.research.google.com/drive/1jyAP5FgSfu0VRrZZ6Rv7lofRYghRFmRF?usp=share_link" . I wanted to learn more about Data Learning and Nueral Networks.
Music Genre Classification seemed to be a easy project from by far , but when I really started doing it made me realise how extensive the work is to be done , just to get "Turkish March" ~ Mozart to be recognised as Classical 


the first problem arised from the collection of dataset , i wondered there being a dataset similar to MNIST so it could be easier to get audio files , with trial error i ende with GTZAN's collection of 1000 "wav" files between 10 genres . I first thought the dataset is less but with computation prowess it requires it certainly is sufficient. 

## Importing the dataset 

- making the directories inside of the /comtent/ folder .

In [1]:
!cd $PROJECT_ROOT
!mkdir -p data/GTZAN
!cd data/GTZAN

THis is was mentioned in the home page of the site but it was not really of the use 

In [2]:
!if [ ! -f ~/.kaggle/kaggle.json ]; then
!    echo "Error: ~/.kaggle/kaggle.json does not exist!"
!    echo "Please create your kaggle.json file from https://www.kaggle.com/<username>/account and place it under ~/.kaggle/kaggle.json, then run this script."
!    exit 1
!fi

/bin/bash: -c: line 2: syntax error: unexpected end of file
Error: ~/.kaggle/kaggle.json does not exist!
Please create your kaggle.json file from https://www.kaggle.com/<username>/account and place it under ~/.kaggle/kaggle.json, then run this script.
/bin/bash: -c: line 1: syntax error near unexpected token `fi'
/bin/bash: -c: line 1: `fi'


- importig the dataset and all its files ,the file named **JAZZ0054** is a corrupted file so had to remove it 

In [3]:
!chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download -d andradaolteanu/gtzan-dataset-music-genre-classification
!unzip gtzan-dataset-music-genre-classification.zip

chmod: cannot access '/root/.kaggle/kaggle.json': No such file or directory
Dataset URL: https://www.kaggle.com/datasets/andradaolteanu/gtzan-dataset-music-genre-classification
License(s): other
 99% 1.20G/1.21G [00:18<00:00, 34.8MB/s]
100% 1.21G/1.21G [00:18<00:00, 71.7MB/s]
Archive:  gtzan-dataset-music-genre-classification.zip
  inflating: Data/features_30_sec.csv  
  inflating: Data/features_3_sec.csv  
  inflating: Data/genres_original/blues/blues.00000.wav  
  inflating: Data/genres_original/blues/blues.00001.wav  
  inflating: Data/genres_original/blues/blues.00002.wav  
  inflating: Data/genres_original/blues/blues.00003.wav  
  inflating: Data/genres_original/blues/blues.00004.wav  
  inflating: Data/genres_original/blues/blues.00005.wav  
  inflating: Data/genres_original/blues/blues.00006.wav  
  inflating: Data/genres_original/blues/blues.00007.wav  
  inflating: Data/genres_original/blues/blues.00008.wav  
  inflating: Data/genres_original/blues/blues.00009.wav  
  inflati

listing the folders iside the main DATA folder

In [ ]:
!ln -s Data/genres_original ./genres


In [ ]:
!wget https://raw.githubusercontent.com/coreyker/dnn-mgr/bdad579ea6cb37b665ea6019fe1026a6ce20cbc7/gtzan/train_filtered.txt
# jazz.00054.wav is corrupted in kaggle source, remove it from train_filtered.txt
!sed -e '/jazz.00054.wav/d' train_filtered.txt > _train_filtered.txt
!mv _train_filtered.txt train_filtered.txt
!wget https://raw.githubusercontent.com/coreyker/dnn-mgr/bdad579ea6cb37b665ea6019fe1026a6ce20cbc7/gtzan/valid_filtered.txt
!wget https://raw.githubusercontent.com/coreyker/dnn-mgr/bdad579ea6cb37b665ea6019fe1026a6ce20cbc7/gtzan/test_filtered.txt

# beat tracking label
!wget http://anasynth.ircam.fr/home/system/files/attachment_uploads/marchand/private/GTZAN-Rhythm_v2_ismir2015_lbd_2015-10-28.tar_.gz


--2024-07-30 11:36:41--  https://raw.githubusercontent.com/coreyker/dnn-mgr/bdad579ea6cb37b665ea6019fe1026a6ce20cbc7/gtzan/train_filtered.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10152 (9.9K) [text/plain]
Saving to: ‘train_filtered.txt’

train_filtered.txt  100%[===================>]   9.91K  --.-KB/s    in 0.001s  

2024-07-30 11:36:41 (11.1 MB/s) - ‘train_filtered.txt’ saved [10152/10152]

--2024-07-30 11:36:42--  https://raw.githubusercontent.com/coreyker/dnn-mgr/bdad579ea6cb37b665ea6019fe1026a6ce20cbc7/gtzan/valid_filtered.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connec

In [4]:
!tar xzvf GTZAN-Rhythm_v2_ismir2015_lbd_2015-10-28.tar_.gz

!cd $PROJECT_ROOT

tar (child): GTZAN-Rhythm_v2_ismir2015_lbd_2015-10-28.tar_.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now


In [5]:
# prompt: list all the files and every file in DATA
!ls -l /content/Data/genres_original



total 40
drwxr-xr-x 2 root root 4096 Aug  1 13:15 blues
drwxr-xr-x 2 root root 4096 Aug  1 13:15 classical
drwxr-xr-x 2 root root 4096 Aug  1 13:15 country
drwxr-xr-x 2 root root 4096 Aug  1 13:15 disco
drwxr-xr-x 2 root root 4096 Aug  1 13:15 hiphop
drwxr-xr-x 3 root root 4096 Aug  1 13:16 jazz
drwxr-xr-x 2 root root 4096 Aug  1 13:15 metal
drwxr-xr-x 2 root root 4096 Aug  1 13:15 pop
drwxr-xr-x 2 root root 4096 Aug  1 13:15 reggae
drwxr-xr-x 2 root root 4096 Aug  1 13:15 rock


### Importing the important libraries but there are several down below 

In [2]:
import librosa
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import soundfile as sf
import audioread


### 1 st attempt 
was to convert the .wav files and reading them as images by plotting there frequencies into a spectogram and then using for extracting the features but as we have seen with images they require a huge dataset to get right and here is where our first problem arises as even the 30 second wav files are over a mb creating a space issue for even converting a loose set of 100000 audios 

In [3]:
def extract_features(file_name):
  try :

    audio , sample_rate = librosa.load(file_name , res_type = "kaiser_fast")
    mel = librosa.feature.melspectrogram(y = audio , sr = sample_rate)
    mel_db = librosa.power_to_db(mel)
    return mel_db
  except (sf.LibsndfileError , audioread.NoBackendError) as e :
    print(f"Error: {file_name , e}")
    return None

In [4]:
path = '/content/Data/genres_original'

In [5]:
gen_name = os.listdir(path)
gen_name.sort()

In [6]:
gen_name

['blues',
 'classical',
 'country',
 'disco',
 'hiphop',
 'jazz',
 'metal',
 'pop',
 'reggae',
 'rock']

In [7]:
Dict = [os.path.join(path , i ) for i in gen_name]
print(Dict)

['/content/Data/genres_original/blues', '/content/Data/genres_original/classical', '/content/Data/genres_original/country', '/content/Data/genres_original/disco', '/content/Data/genres_original/hiphop', '/content/Data/genres_original/jazz', '/content/Data/genres_original/metal', '/content/Data/genres_original/pop', '/content/Data/genres_original/reggae', '/content/Data/genres_original/rock']


In [8]:
Dictionary =  {name: index for index, name in enumerate(gen_name)}


In [9]:
Dictionary

{'blues': 0,
 'classical': 1,
 'country': 2,
 'disco': 3,
 'hiphop': 4,
 'jazz': 5,
 'metal': 6,
 'pop': 7,
 'reggae': 8,
 'rock': 9}

In [10]:
data , labels = [] , []

In [ ]:
for i in Dict:
  for j in os.listdir(i):
    if j.endswith('.wav'):
      mel_spectogram = extract_features(os.path.join(i , j))
      if mel_spectogram is not None:
        data.append(mel_spectogram)
        labels.append(Dictionary[i.split('/')[-1]])


In [ ]:
len(data)

999

In [ ]:
len(labels)

999

importing cv2 because it was required for the available images to be reshaped into a certin size  

In [ ]:
import cv2

In [ ]:
def resize_data(data):
  return cv2.resize(data , (128 , 128))


In [ ]:
r_data = [resize_data(i) for i in data if i is not None]
r_data = np.array(r_data)

In [ ]:
r_data.shape

(999, 128, 128)

In [ ]:
labels = labels[:len(r_data)]
labels = np.array(labels)

In [ ]:
labels.shape

(999,)

In [ ]:
r_data = r_data.reshape(r_data.shape[0] , 128 , 128 , 1)

normalising the data 


In [ ]:
r_data = r_data / 255.0

importing the modules for label and one-hot encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder as le
from tensorflow.keras.utils import to_categorical

In [ ]:
le = le()
labels = le.fit_transform(labels)
labels = to_categorical(labels)

In [ ]:
labels.shape

(999, 10)

importing tts to split the data

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train , X_test , y_train , y_test = train_test_split(r_data , labels , test_size = 0.2 , random_state = 42)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(799, 128, 128, 1)
(200, 128, 128, 1)
(799, 10)
(200, 10)


These are all the necessary libraries for developing a Nueral Network basic 

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import InputLayer , Conv2D , MaxPooling2D , Flatten , Dense , Dropout , BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2

r_s was supposed to be the learning rate 

In [ ]:
r_s = 0.0001

the seen may be 7-8 th model tried of various combinations and it was the best i got with all the tuning done as it gave me 71.8% accuracy , whereas all the other attempts were as low as lying in 30s 

In [ ]:
model = Sequential()
model.add(InputLayer(input_shape = (128 , 128 , 1)))
model.add(Conv2D(16, (5, 5), activation='relu' , kernel_regularizer=l2(r_s)))
model.add(MaxPooling2D((3, 3), strides=(2, 2), padding='same'))
model.add(Conv2D(32, (5, 5), activation='relu' , kernel_regularizer=l2(r_s)))
model.add(MaxPooling2D((3, 3), strides=(2, 2), padding='same'))
model.add(Conv2D(64, (5, 5), activation='relu' , kernel_regularizer=l2(r_s)))
model.add(MaxPooling2D((3, 3), strides=(2, 2), padding='same'))
model.add(Conv2D(128, (5, 5), activation='relu' , kernel_regularizer=l2(r_s)))
model.add(MaxPooling2D((3, 3), strides=(2, 2), padding='same'))
model.add(Flatten())
model.add(Dense(128, activation='relu',kernel_regularizer=l2(r_s)))
model.add(Dropout(0.3))
model.add(Dense(64, activation='relu',kernel_regularizer=l2(r_s)))
model.add(Dense(10, activation='softmax',kernel_regularizer=l2(r_s)))  # Output layer with softmax for classification
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 124, 124, 16)      416       
                                                                 
 max_pooling2d (MaxPooling2  (None, 62, 62, 16)        0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 58, 58, 32)        12832     
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 29, 29, 32)        0         
 g2D)                                                            
                                                                 
 conv2d_2 (Conv2D)           (None, 25, 25, 64)        51264     
                                                                 
 max_pooling2d_2 (MaxPoolin  (None, 13, 13, 64)        0

In [ ]:
model.fit(X_train , y_train , epochs = 150 , batch_size = 64 , validation_data = (X_test , y_test))

Epoch 1/150
13/13 [==============================] - 21s 2s/step - loss: 0.5934 - accuracy: 0.7897 - val_loss: 1.0452 - val_accuracy: 0.6850
Epoch 2/150
13/13 [==============================] - 22s 2s/step - loss: 0.5630 - accuracy: 0.8123 - val_loss: 1.0206 - val_accuracy: 0.6750
Epoch 3/150
13/13 [==============================] - 20s 2s/step - loss: 0.5454 - accuracy: 0.8298 - val_loss: 1.0385 - val_accuracy: 0.6850
Epoch 4/150
13/13 [==============================] - 22s 2s/step - loss: 0.4999 - accuracy: 0.8398 - val_loss: 1.0794 - val_accuracy: 0.7000
Epoch 5/150
13/13 [==============================] - 21s 2s/step - loss: 0.4954 - accuracy: 0.8398 - val_loss: 1.1528 - val_accuracy: 0.6700
Epoch 6/150
13/13 [==============================] - 23s 2s/step - loss: 0.4754 - accuracy: 0.8461 - val_loss: 1.0935 - val_accuracy: 0.6850
Epoch 7/150
13/13 [==============================] - 20s 2s/step - loss: 0.4618 - accuracy: 0.8536 - val_loss: 1.1184 - val_accuracy: 0.6850
Epoch 8/150
1

In [ ]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report
y_pred = model.predict(X_test)
y_pred = np.argmax(y_pred , axis = 1)
y_test2 = np.argmax(y_test , axis = 1)

7/7 [==============================] - 2s 237ms/step


In [ ]:
print(accuracy_score(y_test2 , y_pred)*100 ,'%')
print(confusion_matrix(y_test2 , y_pred))
print(classification_report(y_test2 , y_pred))

71.5 %
[[14  0  1  1  0  2  0  0  1  2]
 [ 0 12  0  0  0  0  0  0  0  0]
 [ 1  0 14  0  0  3  0  1  0  5]
 [ 3  0  1 12  1  0  1  1  0  3]
 [ 0  0  0  1 12  0  0  1  0  1]
 [ 0  3  0  0  0 23  0  0  0  1]
 [ 0  0  0  0  0  0 17  0  0  1]
 [ 0  0  1  2  0  0  0 14  2  0]
 [ 0  0  1  1  1  0  0  0 17  2]
 [ 1  0  1  5  2  0  3  0  0  8]]
              precision    recall  f1-score   support

           0       0.74      0.67      0.70        21
           1       0.80      1.00      0.89        12
           2       0.74      0.58      0.65        24
           3       0.55      0.55      0.55        22
           4       0.75      0.80      0.77        15
           5       0.82      0.85      0.84        27
           6       0.81      0.94      0.87        18
           7       0.82      0.74      0.78        19
           8       0.85      0.77      0.81        22
           9       0.35      0.40      0.37        20

    accuracy                           0.71       200
   macro avg

Used Gemini to commit these into REPO 

In [ ]:
# prompt: save the modek and commit it to my repo https://github.com/TrishankV/Music-Genre-Classifier/blob/main/Music_Genre_Classification.ipynb

# Save the model
# model.save('music_genre_classifier1.h5')

# You'll need to set up your GitHub credentials and configure the repository for this to work.
# This is a basic example and may need adjustments based on your specific setup.

# Install necessary libraries
!pip install -q pygithub

from github import Github
from google.colab import files

# Replace with your GitHub personal access token
access_token = ""

# Replace with your GitHub username and repository name
username = "TrishankV"
repo_name = "Music-Genre-Classifier"

# Authenticate with GitHub
g = Github(access_token)
repo = g.get_user().get_repo(repo_name)

# Upload the model file
with open('music_genre_classifier1.h5', 'rb') as f:
  repo.create_file(
      path="music_genre_classifier1.h5",
      message="Added trained music genre classifier model",
      content=f.read(),
      branch="main"  # Change to your branch if needed
  )

print("Model saved and committed to GitHub!")


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 354.4/354.4 kB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 856.7/856.7 kB 16.1 MB/s eta 0:00:00
Model saved and committed to GitHub!


### Audio augmentaion 
it is the method of augmenitng audio in more waus to get out more extractable features out of it , it didnt work 

In [ ]:
  !pip install audiomentations

In [ ]:
from audiomentations import Compose, AddGaussianNoise, TimeStretch, PitchShift, Shift

Shift is deprecated 

In [ ]:
augment = Compose([
    AddGaussianNoise(min_amplitude = 0.001 ,
                     max_amplitude = 0.015 ,
                     p = 0.5) ,
    TimeStretch(min_rate = 0.8 ,
                max_rate = 1.25 ,
                p = 0.5 ),
    PitchShift(min_semitones = -4 ,
               max_semitones = 4 ,
               p = 0.5)
])

In [ ]:
def augment_audio(y):
    # Apply augmentation
    y_augmented = augment(samples=y, sample_rate=22050)
    return y_augmented

In [ ]:
def extract_features2(file_name, fixed_length=128):
    try:
        audio, sample_rate = librosa.load(file_name, res_type='kaiser_fast')
        # Apply augmentation
        audio = augment_audio(audio)
        # Extract Mel spectrogram features
        mel = librosa.feature.melspectrogram(y=audio, sr=sample_rate)
        mel_db = librosa.power_to_db(mel)

        # Pad or truncate to fixed length
        if mel_db.shape[1] > fixed_length:
            mel_db = mel_db[:, :fixed_length]
        else:
            padding = fixed_length - mel_db.shape[1]
            mel_db = np.pad(mel_db, ((0, 0), (0, padding)), mode='constant')

        return mel_db
    except (sf.LibsndfileError, audioread.NoBackendError) as e:
        print(f"Error: {file_name} - {e}")
        return None

In [ ]:
x_data = []
y_data = []

for class_idx, class_name in enumerate(gen_name):
    class_dir = os.path.join(path, class_name)
    for file_name in os.listdir(class_dir):
        file_path = os.path.join(class_dir, file_name)
        features = extract_features2(file_path)
        if features is not None:
            x_data.append(features)
            y_data.append(class_idx)



<ipython-input-58-6bf8d1100b43>:3: UserWarning: PySoundFile failed. Trying audioread instead.
  audio, sample_rate = librosa.load(file_name, res_type='kaiser_fast')
/usr/local/lib/python3.10/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)


Error: /content/Data/genres_original/jazz/jazz.00054.wav - 


In [ ]:
x_data = np.array(x_data)
y_data = to_categorical(np.array(y_data), num_classes=len(gen_name))

In [ ]:
x_train, x_val, Y_train, y_val = train_test_split(x_data, y_data, test_size=0.2, random_state=42)


In [ ]:
x_train.shape

(799, 128, 128)

Model no 12


In [ ]:
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=((128, 128 , 1)), kernel_regularizer=l2(r_s)))
model.add(BatchNormalization())
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', kernel_regularizer=l2(r_s)))
model.add(BatchNormalization())
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu', kernel_regularizer=l2(r_s)))
model.add(BatchNormalization())
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu', kernel_regularizer=l2(r_s)))
model.add(Dropout(0.4))
model.add(Dense(64, activation='relu', kernel_regularizer=l2(r_s)))
model.add(Dense(10, activation='softmax', kernel_regularizer=l2(r_s)))

# Compile the model
optimizer = Adam(learning_rate=0.0001)
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])


In [ ]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_11 (Conv2D)          (None, 126, 126, 32)      320       
                                                                 
 batch_normalization_7 (Bat  (None, 126, 126, 32)      128       
 chNormalization)                                                
                                                                 
 max_pooling2d_11 (MaxPooli  (None, 63, 63, 32)        0         
 ng2D)                                                           
                                                                 
 conv2d_12 (Conv2D)          (None, 61, 61, 64)        18496     
                                                                 
 batch_normalization_8 (Bat  (None, 61, 61, 64)        256       
 chNormalization)                                                
                                                      

In [ ]:
import tensorflow as tf

Becasue it was taking a lot of time so had to stop it as soon as it gets to a stable accuracy ,. 

In [ ]:
history = model.fit(x_train, Y_train,batch_size = 16 ,  epochs=50, validation_data=(x_val, y_val) ,
                    callbacks = [
                  tf.keras.callbacks.EarlyStopping(
                      monitor='val_loss',
                      patience=3,
                      restore_best_weights=True) ,
                    tf.keras.callbacks.ReduceLROnPlateau(
                      monitor='val_loss',
                      factor=0.2,
                      patience=2,
                      min_lr=0.001)])


Epoch 1/50
50/50 [==============================] - 34s 675ms/step - loss: 0.2563 - accuracy: 0.9362 - val_loss: 2.0289 - val_accuracy: 0.4350 - lr: 1.0000e-04
Epoch 2/50
50/50 [==============================] - 31s 617ms/step - loss: 0.2822 - accuracy: 0.9237 - val_loss: 1.9147 - val_accuracy: 0.4500 - lr: 1.0000e-04
Epoch 3/50
50/50 [==============================] - 36s 720ms/step - loss: 0.2424 - accuracy: 0.9337 - val_loss: 1.9734 - val_accuracy: 0.4300 - lr: 1.0000e-04
Epoch 4/50
50/50 [==============================] - 32s 649ms/step - loss: 0.2301 - accuracy: 0.9424 - val_loss: 2.0026 - val_accuracy: 0.4150 - lr: 1.0000e-04
Epoch 5/50
50/50 [==============================] - 31s 612ms/step - loss: 0.2066 - accuracy: 0.9524 - val_loss: 1.9600 - val_accuracy: 0.4500 - lr: 1.0000e-04


In [ ]:
Y_train.shape

(799, 10)

In [ ]:
# prompt: print accutrcat confession matrix

y_pred = model.predict(x_val)
y_pred = np.argmax(y_pred, axis=1)
y_test2 = np.argmax(y_val, axis=1)
print(accuracy_score(y_test2, y_pred) * 100, '%')
print(confusion_matrix(y_test2, y_pred))
print(classification_report(y_test2, y_pred))


7/7 [==============================] - 2s 243ms/step
45.0 %
[[ 9  1  0  1  0  6  3  0  0  1]
 [ 0  9  1  0  0  2  0  0  0  0]
 [ 3  3  7  0  4  5  0  0  1  1]
 [ 5  1  1  4  1  0  2  3  3  2]
 [ 1  0  0  0  5  0  2  0  6  1]
 [ 1  9  2  0  2 12  0  0  1  0]
 [ 1  0  0  0  0  0 17  0  0  0]
 [ 1  1  0  2  2  1  0  8  4  0]
 [ 3  0  2  0  0  0  0  0 17  0]
 [ 2  1  1  3  0  1  7  2  1  2]]
              precision    recall  f1-score   support

           0       0.35      0.43      0.38        21
           1       0.36      0.75      0.49        12
           2       0.50      0.29      0.37        24
           3       0.40      0.18      0.25        22
           4       0.36      0.33      0.34        15
           5       0.44      0.44      0.44        27
           6       0.55      0.94      0.69        18
           7       0.62      0.42      0.50        19
           8       0.52      0.77      0.62        22
           9       0.29      0.10      0.15        20

    accuracy 

In [ ]:
# prompt: save and commit this model

# Save the model
model.save('music_genre_classifier2-45.h5')

# You'll need to set up your GitHub credentials and configure the repository for this to work.
# This is a basic example and may need adjustments based on your specific setup.

# Install necessary libraries
# !pip install -q pygithub


# Replace with your GitHub personal access token
access_token = "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"

# # Replace with your GitHub username and repository name
# username = "TrishankV"
# repo_name = "Music-Genre-Classifier"

# Authenticate with GitHub
g = Github(access_token)
repo = g.get_user().get_repo(repo_name)

# Upload the model file
with open('music_genre_classifier2-45.h5', 'rb') as f:
  repo.create_file(
      path="music_genre_classifier2-45.h5",
      message="Added trained music genre classifier model with augmentation",
      content=f.read(),
      branch="main"  # Change to your branch if needed
  )

print("Model saved and committed to GitHub!")


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


Model saved and committed to GitHub!


LEts try a RNN

Seaarched and found out that Reccurrent NN are also used for Audio classfication nut it didmt work really that much

In [ ]:
from keras.layers import LSTM , Reshape , Bidirectional

Model NO 15

In [ ]:
RNN = Sequential()
RNN.add(InputLayer(input_shape=(128, 128, 1)))
RNN.add(Conv2D(32, (3, 3), activation='relu', kernel_regularizer=l2(0.0001)))
RNN.add(BatchNormalization())
RNN.add(MaxPooling2D((2, 2)))
RNN.add(Conv2D(64, (3, 3), activation='relu', kernel_regularizer=l2(0.0001)))
RNN.add(BatchNormalization())
RNN.add(MaxPooling2D((2, 2)))
RNN.add(Conv2D(128, (3, 3), activation='relu', kernel_regularizer=l2(0.0001)))
RNN.add(BatchNormalization())
RNN.add(MaxPooling2D((2, 2)))
# # RNN.add(Flatten())
# RNN.add(Reshape((14 * 14, 128)))
# RNN.add(LSTM(128, return_sequences=True))
# RNN.add(LSTM(128))
RNN.add(Flatten())
RNN.add(Dense(256, activation='relu', kernel_regularizer=l2(0.0001)))
RNN.add(Dropout(0.5))
RNN.add(Dense(128, activation='relu', kernel_regularizer=l2(0.0001)))
RNN.add(Dropout(0.5))
RNN.add(Dense(64, activation='relu', kernel_regularizer=l2(0.0001)))
RNN.add(Dense(10, activation='softmax', kernel_regularizer=l2(0.0001)))

# Compile the RNN
optimizer = Adam(learning_rate=0.0001)
RNN.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])



In [ ]:
RNN.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_20 (Conv2D)          (None, 126, 126, 32)      320       
                                                                 
 batch_normalization_16 (Ba  (None, 126, 126, 32)      128       
 tchNormalization)                                               
                                                                 
 max_pooling2d_20 (MaxPooli  (None, 63, 63, 32)        0         
 ng2D)                                                           
                                                                 
 conv2d_21 (Conv2D)          (None, 61, 61, 64)        18496     
                                                                 
 batch_normalization_17 (Ba  (None, 61, 61, 64)        256       
 tchNormalization)                                               
                                                      

In [ ]:
RNN.fit(X_train , y_train , epochs = 50 , batch_size = 64 , validation_data = (X_test , y_test),
              callbacks = [
                  tf.keras.callbacks.EarlyStopping(
                      monitor='val_loss',
                      patience=3,
                      restore_best_weights=True) ,
                    tf.keras.callbacks.ReduceLROnPlateau(
                      monitor='val_loss',
                      factor=0.2,
                      patience=2,
                      min_lr=0.001)])

Epoch 1/50
13/13 [==============================] - 37s 3s/step - loss: 3.3423 - accuracy: 0.1339 - val_loss: 2.3948 - val_accuracy: 0.1050 - lr: 1.0000e-04
Epoch 2/50
13/13 [==============================] - 35s 3s/step - loss: 2.6437 - accuracy: 0.1552 - val_loss: 2.5528 - val_accuracy: 0.1050 - lr: 1.0000e-04
Epoch 3/50
13/13 [==============================] - 34s 3s/step - loss: 2.3756 - accuracy: 0.1677 - val_loss: 2.8228 - val_accuracy: 0.1050 - lr: 1.0000e-04
Epoch 4/50
13/13 [==============================] - 37s 3s/step - loss: 2.2809 - accuracy: 0.2153 - val_loss: 3.1774 - val_accuracy: 0.1050 - lr: 1.0000e-04


In [ ]:
# prompt: print the accuracy precision and confusion matrix

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# ... (your existing code) ...

# Predict on the test set
y_pred = RNN.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

# Calculate metrics
accuracy = accuracy_score(y_true, y_pred_classes)
precision = precision_score(y_true, y_pred_classes, average='weighted')
recall = recall_score(y_true, y_pred_classes, average='weighted')
f1 = f1_score(y_true, y_pred_classes, average='weighted')
conf_matrix = confusion_matrix(y_true, y_pred_classes)

# Print the results
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion Matrix:\n", conf_matrix)


7/7 [==============================] - 2s 235ms/step
Accuracy: 0.105
Precision: 0.011025
Recall: 0.105
F1-score: 0.01995475113122172
Confusion Matrix:
 [[21  0  0  0  0  0  0  0  0  0]
 [12  0  0  0  0  0  0  0  0  0]
 [24  0  0  0  0  0  0  0  0  0]
 [22  0  0  0  0  0  0  0  0  0]
 [15  0  0  0  0  0  0  0  0  0]
 [27  0  0  0  0  0  0  0  0  0]
 [18  0  0  0  0  0  0  0  0  0]
 [19  0  0  0  0  0  0  0  0  0]
 [22  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy = 10%

Wanted to use tranformer , this was suggested by GPT for a ttansfore block had hopes that it would work but it didmt worled that much 

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, BatchNormalization, MaxPooling2D, Flatten, Dense, Dropout, Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from tensorflow.keras import Model
from tensorflow.keras.layers import LayerNormalization, MultiHeadAttention, Add

class TransformerBlock(tf.keras.layers.Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, rate=0.1):
        super(TransformerBlock, self).__init__()
        self.att = MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim)
        self.ffn = Sequential([
            Dense(ff_dim, activation="relu"),
            Dense(embed_dim),
        ])
        self.layernorm1 = LayerNormalization(epsilon=1e-6)
        self.layernorm2 = LayerNormalization(epsilon=1e-6)
        self.dropout1 = Dropout(rate)
        self.dropout2 = Dropout(rate)

    def call(self, inputs, training):
        attn_output = self.att(inputs, inputs)
        attn_output = self.dropout1(attn_output, training=training)
        out1 = self.layernorm1(inputs + attn_output)
        ffn_output = self.ffn(out1)
        ffn_output = self.dropout2(ffn_output, training=training)
        return self.layernorm2(out1 + ffn_output)

def create_model(input_shape, num_classes):
    inputs = Input(shape=input_shape)

    # Convolutional layers
    x = Conv2D(32, (3, 3), activation='relu', kernel_regularizer=l2(r_s))(inputs)
    x = BatchNormalization()(x)
    x = MaxPooling2D((2, 2))(x)
    x = Conv2D(64, (3, 3), activation='relu', kernel_regularizer=l2(r_s))(x)
    x = BatchNormalization()(x)
    x = MaxPooling2D((2, 2))(x)
    x = Conv2D(128, (3, 3), activation='relu', kernel_regularizer=l2(r_s))(x)
    x = BatchNormalization()(x)
    x = MaxPooling2D((2, 2))(x)

    # Flatten the conv output
    x = Flatten()(x)

    # Reshape for Transformer
    x = Dense(256, activation='relu')(x)
    x = tf.expand_dims(x, axis=1)

    # Transformer block
    transformer_block = TransformerBlock(embed_dim=256, num_heads=8, ff_dim=512)
    x = transformer_block(x)
    x = tf.squeeze(x, axis=1)

    # Dense layers
    x = Dense(128, activation='relu', kernel_regularizer=l2(r_s))(x)
    x = Dropout(0.4)(x)
    x = Dense(64, activation='relu', kernel_regularizer=l2(r_s))(x)
    outputs = Dense(num_classes, activation='softmax', kernel_regularizer=l2(r_s))(x)

    model = Model(inputs=inputs, outputs=outputs)
    return model

# Parameters
input_shape = (128, 128, 1)
num_classes = 10
r_s = 0.01

# Create the model
model = create_model(input_shape, num_classes)

# Compile the model
optimizer = Adam(learning_rate=0.0001)
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

# Print the model summary
model.summary()


Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_6 (InputLayer)        [(None, 128, 128, 1)]     0         
                                                                 
 conv2d_23 (Conv2D)          (None, 126, 126, 32)      320       
                                                                 
 batch_normalization_19 (Ba  (None, 126, 126, 32)      128       
 tchNormalization)                                               
                                                                 
 max_pooling2d_23 (MaxPooli  (None, 63, 63, 32)        0         
 ng2D)                                                           
                                                                 
 conv2d_24 (Conv2D)          (None, 61, 61, 64)        18496     
                                                                 
 batch_normalization_20 (Ba  (None, 61, 61, 64)        256   

In [ ]:
model.fit(X_train , y_train , epochs = 50 , batch_size = 64 , validation_data = (X_test , y_test))

Epoch 1/50
13/13 [==============================] - 43s 3s/step - loss: 6.2938 - accuracy: 0.1802 - val_loss: 7.1705 - val_accuracy: 0.1100
Epoch 2/50
13/13 [==============================] - 35s 3s/step - loss: 5.9156 - accuracy: 0.3116 - val_loss: 6.9803 - val_accuracy: 0.1100
Epoch 3/50
13/13 [==============================] - 34s 3s/step - loss: 5.7279 - accuracy: 0.3755 - val_loss: 6.9719 - val_accuracy: 0.1100
Epoch 4/50
13/13 [==============================] - 34s 3s/step - loss: 5.4752 - accuracy: 0.4718 - val_loss: 6.7074 - val_accuracy: 0.1100
Epoch 5/50
13/13 [==============================] - 36s 3s/step - loss: 5.2068 - accuracy: 0.5432 - val_loss: 6.5877 - val_accuracy: 0.1100
Epoch 6/50
13/13 [==============================] - 34s 3s/step - loss: 4.8945 - accuracy: 0.6633 - val_loss: 6.4737 - val_accuracy: 0.1100
Epoch 7/50
13/13 [==============================] - 37s 3s/step - loss: 4.6191 - accuracy: 0.7822 - val_loss: 6.3740 - val_accuracy: 0.1100
Epoch 8/50
13/13 [==

In [ ]:
# prompt: print the accuracy , precision % and confusion matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Predict on the test set
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

# Calculate metrics
accuracy = accuracy_score(y_true, y_pred_classes)
precision = precision_score(y_true, y_pred_classes, average='weighted')
recall = recall_score(y_true, y_pred_classes, average='weighted')
f1 = f1_score(y_true, y_pred_classes, average='weighted')
conf_matrix = confusion_matrix(y_true, y_pred_classes)

# Print the results
print("Accuracy:", accuracy * 100, "%")
print("Precision:", precision * 100, "%")
print("Recall:", recall * 100, "%")
print("F1-score:", f1 * 100, "%")
print("Confusion Matrix:\n", conf_matrix)


7/7 [==============================] - 3s 453ms/step
Accuracy: 46.5 %
Precision: 70.01933777429467 %
Recall: 46.5 %
F1-score: 43.219846331123314 %
Confusion Matrix:
 [[ 9  0  0  0  4  4  4  0  0  0]
 [ 0 10  0  0  0  1  0  0  0  1]
 [ 2  0  2  0  6  5  6  1  1  1]
 [ 1  0  0  3  8  0 10  0  0  0]
 [ 0  0  0  0 12  0  3  0  0  0]
 [ 0  3  0  0  0 22  2  0  0  0]
 [ 0  0  0  0  0  0 18  0  0  0]
 [ 1  1  0  0  5  0  1 10  0  1]
 [ 0  0  0  0 19  0  0  0  3  0]
 [ 2  0  0  0  4  0 10  0  0  4]]


In [ ]:
# prompt: save the model to '/content'

# ... (your existing code) ...

# Save the model
model.save('/content/music_genre_transformer.h5')


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


### YAMNET Classification 


this is pretrained model for YAMNET classification 

In [ ]:
pip install tensorflow_io

In [ ]:
import tensorflow_hub as hub
import tensorflow_io as tfio
yamnet = hub.load('https://tfhub.dev/google/yamnet/1')

In [ ]:
def load_wav(filename):
  auido , sample_rate = librosa.load(filename , sr = 16000 , mono = True)
  # auido = tf.cast(auido , tf.float32)
  return auido

In [ ]:
def extract_features3(wav):
  waveform = tf.convert_to_tensor(wav , dtype=tf.float32)
  waveform = tf.reshape(waveform , [-1])
  scores , embedding  , spectrogram = yamnet(waveform)
  return embedding.numpy().flatten()

PAdding hte array becuase the features were returnig a shape with + inhomegenous part 

In [ ]:
import numpy as np

def pad_sequences(sequences, maxlen=None, dtype='int32', padding='post', truncating='post', value=0.0):

    lengths = [len(s) for s in sequences]
    if maxlen is None:
        maxlen = np.max(lengths)

    num_samples = len(sequences)
    padded_sequences = np.full((num_samples, maxlen), value, dtype=dtype)
    for i, s in enumerate(sequences):
        if truncating == 'pre':
            trunc = s[-maxlen:]
        elif truncating == 'post':
            trunc = s[:maxlen]
        else:
            raise ValueError('Truncating type "%s" not understood' % truncating)

        if padding == 'post':
            padded_sequences[i, :len(trunc)] = trunc
        elif padding == 'pre':
            padded_sequences[i, -len(trunc):] = trunc
        else:
            raise ValueError('Padding type "%s" not understood' % padding)

    return padded_sequences


# After extracting features:
nd_padded = pad_sequences(nd, dtype='float32')

# Now you can try creating the NumPy array:
nd_array = np.array(nd_padded)

In [ ]:
nd , ns = [] , []

In [ ]:
for genre_dir in Dict:
  genre_label = genre_dir.split('/')[-1]
  if genre_label not in Dictionary:
    continue
  label = Dictionary[genre_label]
  for file_name in os.listdir (genre_dir):
    if file_name.endswith('.wav'):
      file_path = os.path.join(genre_dir, file_name)
      wav_data = load_wav(file_path)
      if wav_data is not None:
        features = extract_features3(wav_data)
        if features is not None:
          nd.append(features)
          ns.append(label)


In [ ]:
ns = np.array(ns)

In [ ]:
nd_array.shape

In [ ]:
nd_array = nd_array.reshape(nd_array.shape[0] , -1)

In [ ]:
from tensorflow.keras.layers import LSTM , Reshape , Bidirectional

In [ ]:
dif_shpe = (nd_array.shape[1] ,)
new_model = Sequential()
new_model.add(InputLayer(input_shape=dif_shpe))
new_model.add(Dense(256, activation='relu', kernel_regularizer=l2(0.01)))
new_model.add(BatchNormalization())
new_model.add(Dropout(0.5))
new_model.add(Dense(256, activation='relu', kernel_regularizer=l2(0.01)))
new_model.add(BatchNormalization())
new_model.add(Dropout(0.5))
new_model.add(Dense(128, activation='relu', kernel_regularizer=l2(0.01)))
new_model.add(BatchNormalization())
new_model.add(Dropout(0.5))
new_model.add(Dense(64, activation='relu', kernel_regularizer=l2(0.01)))
new_model.add(BatchNormalization())
new_model.add(Dropout(0.5))
new_model.add(Dense(10, activation='softmax'))

new_model.compile(optimizer = 'adam' , loss = 'sparse_categorical_crossentropy' , metrics = ['accuracy'])

In [ ]:
new_model.summary()

Model: "sequential_20"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_92 (Dense)            (None, 256)               16515328  
                                                                 
 batch_normalization_26 (Ba  (None, 256)               1024      
 tchNormalization)                                               
                                                                 
 dropout_56 (Dropout)        (None, 256)               0         
                                                                 
 dense_93 (Dense)            (None, 256)               65792     
                                                                 
 batch_normalization_27 (Ba  (None, 256)               1024      
 tchNormalization)                                               
                                                                 
 dropout_57 (Dropout)        (None, 256)             

In [ ]:
new_model.fit(nd_array , ns , epochs = 50 , batch_size = 64 , validation_split = 0.25 ,
              callbacks = [
                  tf.keras.callbacks.EarlyStopping(
                      monitor='val_loss',
                      patience=3,
                      restore_best_weights=True) ,
                    tf.keras.callbacks.ReduceLROnPlateau(
                      monitor='val_loss',
                      factor=0.2,
                      patience=2,
                      min_lr=0.001)

          ])

Epoch 1/50
12/12 [==============================] - 9s 543ms/step - loss: 11.9279 - accuracy: 0.2043 - val_loss: 13.2408 - val_accuracy: 0.0000e+00 - lr: 0.0010
Epoch 2/50
12/12 [==============================] - 5s 405ms/step - loss: 11.2043 - accuracy: 0.4045 - val_loss: 13.5314 - val_accuracy: 0.0040 - lr: 0.0010
Epoch 3/50
12/12 [==============================] - 4s 345ms/step - loss: 10.3754 - accuracy: 0.5728 - val_loss: 12.6313 - val_accuracy: 0.0000e+00 - lr: 0.0010
Epoch 4/50
12/12 [==============================] - 6s 516ms/step - loss: 9.5921 - accuracy: 0.6716 - val_loss: 11.7718 - val_accuracy: 0.0000e+00 - lr: 0.0010
Epoch 5/50
12/12 [==============================] - 5s 405ms/step - loss: 8.7680 - accuracy: 0.7356 - val_loss: 10.8265 - val_accuracy: 0.0160 - lr: 0.0010
Epoch 6/50
12/12 [==============================] - 4s 371ms/step - loss: 8.0346 - accuracy: 0.7610 - val_loss: 10.1398 - val_accuracy: 0.0440 - lr: 0.0010
Epoch 7/50
12/12 [==============================]

In [ ]:
# prompt: check the accuracy

# ... (your existing code) ...

# Evaluate the model
loss, accuracy = new_model.evaluate(nd_array, ns, verbose=0)
print('Accuracy: %.2f%%' % (accuracy * 100))


Accuracy: 78.98%


In [ ]:
# prompt: saw the model and commit to the main branch

# ... (your existing code) ...

# Save the model
new_model.save('/content/yamnet_classifier.h5')

# You'll need to set up your GitHub credentials and configure the repository for this to work.
# This is a basic example and may need adjustments based on your specific setup.

# Install necessary libraries
# !pip install -q pygithub


# Replace with your GitHub personal access token
access_token = "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"

# Replace with your GitHub username and repository name
username = "TrishankV"
repo_name = "Music-Genre-Classifier"

# Authenticate with GitHub
g = Github(access_token)
repo = g.get_user().get_repo(repo_name)

# Upload the model file
with open('/content/yamnet_classifier.h5', 'rb') as f:
  repo.create_file(
      path="yamnet_classifier.h5",
      message="Added yamnet classifier model",
      content=f.read(),
      branch="main"  # Change to your branch if needed
  )

print("Model saved and committed to GitHub!")


### MIT AST pretrained model 

In [16]:
import torch
import torchaudio

In [17]:
Dict

['/content/Data/genres_original/blues',
 '/content/Data/genres_original/classical',
 '/content/Data/genres_original/country',
 '/content/Data/genres_original/disco',
 '/content/Data/genres_original/hiphop',
 '/content/Data/genres_original/jazz',
 '/content/Data/genres_original/metal',
 '/content/Data/genres_original/pop',
 '/content/Data/genres_original/reggae',
 '/content/Data/genres_original/rock']

In [18]:
Dictionary

{'blues': 0,
 'classical': 1,
 'country': 2,
 'disco': 3,
 'hiphop': 4,
 'jazz': 5,
 'metal': 6,
 'pop': 7,
 'reggae': 8,
 'rock': 9}

In [11]:
def get_audio_files(genre_dir):
    audio_files = []
    for i in genre_dir :
      genre = i.split('/')[-1]
      lab = Dictionary[genre]
      for j in os.listdir(i):
        # print(j)
        if j.endswith('.wav'):
          file_path = os.path.join(i, j)
          audio_files.append({"audio": file_path , "label" : lab})
    return audio_files

In [12]:
n_d = get_audio_files(Dict)

In [ ]:
n_d[1]

{'audio': '/content/Data/genres_original/blues/blues.00018.wav', 'label': 0}

In [ ]:
training_size = int(0.8 * len(n_d))
training_data = n_d[:training_size]
testing_data = n_d[training_size:]

installing datasets 

In [ ]:
pip install datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 547.8/547.8 kB 29.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 10.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.1/316.1 kB 19.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.9/39.9 MB 19.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 12.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 16.8 MB/s eta 0:00:00
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 14.0.2
    Uninstalling pyarrow-14.0.2:
      Successfully uninstalled pyarrow-14.0.2
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.6.1
    Uninstalling fsspec-2024.6.1:
  

In [ ]:
from datasets import Dataset , DatasetDict , load_dataset , Audio
from transformers import AutoFeatureExtractor , ASTForAudioClassification , TrainingArguments , Trainer

In [ ]:
dataset_dict = DatasetDict({
    "train": Dataset.from_list(training_data).cast_column("audio", Audio(sampling_rate=16000)),
    "validation": Dataset.from_list(testing_data).cast_column("audio", Audio(sampling_rate=16000)),
})

In [ ]:
fe = AutoFeatureExtractor.from_pretrained("MIT/ast-finetuned-audioset-10-10-0.4593")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


preprocessor_config.json:   0%|          | 0.00/297 [00:00<?, ?B/s]

In [ ]:
astmodel = ASTForAudioClassification.from_pretrained("MIT/ast-finetuned-audioset-10-10-0.4593")

config.json:   0%|          | 0.00/26.8k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/346M [00:00<?, ?B/s]

In [ ]:
# def preprocessing(examples):
#     audio_arrays = [example["audio"]["array"] for example in examples["audio"]]
#     inputs = fe(audio_arrays, sampling_rate=16000, return_tensors="pt", padding=True)
#     inputs["labels"] = examples["label"]
#     return inputs

maping the files in a dataset dicitonary so it can be read 

In [ ]:
encoded_Data = dataset.map(preprocessing , remove_columns = ["audio"] , batched = True)

In [ ]:
def preprocessing(examples):
    audio_arrays = [x["array"] for x in examples["audio"]] # Access 'array' directly within each audio example
    inputs = fe(audio_arrays, sampling_rate=16000, return_tensors="pt", padding=True)
    inputs["labels"] = examples["label"]
    return inputs

encoded_Data = dataset_dict.map(preprocessing, remove_columns=["audio"], batched=True) # No change here

Map:   0%|          | 0/799 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

In [ ]:
encoded_Data

DatasetDict({
    train: Dataset({
        features: ['label', 'input_values', 'labels'],
        num_rows: 799
    })
    validation: Dataset({
        features: ['label', 'input_values', 'labels'],
        num_rows: 200
    })
})

In [ ]:
encoded_dataset = encoded_Data.rename_column("label", "labels")


In [ ]:
training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=4,  # Adjust batch size if needed
    per_device_eval_batch_size=4,
    num_train_epochs=3,
    weight_decay=0.01,
    fp16=True,  # Ensure mixed precision training is enabled
)


/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(


In [ ]:
from datasets import load_metric

In [ ]:
from transformers import TrainerCallback

class MyCallback(TrainerCallback):
    def on_evaluate(self, args, state, control, **kwargs):
        print(f"Step {state.global_step}: Evaluation Accuracy: {state.log_history[-1]['eval_accuracy']}")

In [ ]:
metric = load_metric("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = torch.argmax(logits, dim=-1)
    return metric.compute(predictions=predictions, references=labels)

trainer = Trainer(
    model=astmodel,
    args=training_args,
    train_dataset=encoded_Data["train"],
    eval_dataset=encoded_Data["validation"],
    tokenizer=fe,
    compute_metrics=compute_metrics,
)

This was a very computationally heavey tast as it ETAed over 12 hours :( and the runtime exhausted and crashed overnight so it wasnt trained fully :(

In [ ]:

trainer.train()
trainer.save_model("/content/drive/MyDrive/music_genre_classifier/ast_model")


TypeError: argmax(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [ ]:

# Evaluate the model
results = trainer.evaluate()
print(f"Final evaluation results: {results}")

In [ ]:
# prompt: save. the astmodel such that it could be used again

trainer.save_model("/content/drive/MyDrive/music_genre_classifier/ast_model")


THE Model which worked the best was using VGGISH checkpoints to convert the data into the best fearture it could extract possible 

In [20]:
!git clone https://github.com/tensorflow/models.git
!cd models/research/audioset/vggish
!pip install -r requirements.txt

Cloning into 'models'...
remote: Enumerating objects: 97764, done.
remote: Counting objects: 100% (278/278), done.
remote: Compressing objects: 100% (184/184), done.
remote: Total 97764 (delta 95), reused 252 (delta 78), pack-reused 97486
Receiving objects: 100% (97764/97764), 617.37 MiB | 21.27 MiB/s, done.
Resolving deltas: 100% (71082/71082), done.
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'


In [21]:
!wget https://storage.googleapis.com/audioset/vggish_model.ckpt
!wget https://storage.googleapis.com/audioset/vggish_pca_params.npz


--2024-08-01 13:18:04--  https://storage.googleapis.com/audioset/vggish_model.ckpt
Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.2.207, 74.125.137.207, 142.250.101.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.251.2.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 291108469 (278M) [application/octet-stream]
Saving to: ‘vggish_model.ckpt’

vggish_model.ckpt   100%[===================>] 277.62M  55.3MB/s    in 5.0s    

2024-08-01 13:18:10 (55.3 MB/s) - ‘vggish_model.ckpt’ saved [291108469/291108469]

--2024-08-01 13:18:10--  https://storage.googleapis.com/audioset/vggish_pca_params.npz
Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.2.207, 74.125.137.207, 142.250.101.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.251.2.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 73020 (71K) [application/octet-stream]
Saving to: ‘vggish_pca_pa

In [18]:
import sys
sys.path.append('/content/models/research/audioset/vggish')


In [19]:
import vggish_input , vggish_params , vggish_slim

In [24]:
pip install resampy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 38.8 MB/s eta 0:00:00


In [13]:
pca_p = '/content/vggish_pca_params.npz'
c_p = '/content/vggish_model.ckpt'

In [14]:
def extract_label_from_filename(filename):
    # Assuming the label is the first part of the filename before an underscore
    label = filename.split('_')[0]
    return label


In [15]:
import tensorflow as tf

In [16]:
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

In [20]:
embeddings = [] # Initialize embeddings as a list
labels = []
with tf.Graph().as_default() , tf.compat.v1.Session() as sess :
  vggish_slim.define_vggish_slim(training = False)
  # Assuming 'c_p' is defined somewhere earlier in the user's code
  vggish_slim.load_vggish_slim_checkpoint(sess , c_p)
  features_tensor = sess.graph.get_tensor_by_name(vggish_params.INPUT_TENSOR_NAME)
  embedding_tensor = sess.graph.get_tensor_by_name(vggish_params.OUTPUT_TENSOR_NAME)

  for item in n_d:
    audio_path = item['audio']
    label = item['label']
    examples_batch = vggish_input.wavfile_to_examples(audio_path)
    [embedding] = sess.run([embedding_tensor], feed_dict={features_tensor: examples_batch})
    embeddings.append(embedding) # Append to the embeddings list
    labels.append(label)

# Convert lists to numpy arrays outside the loop
embeddings = np.array(embeddings)
labels = np.array(labels)

# Save embeddings and labels
np.save('embeddings.npy', embeddings)
np.save('labels.npy', labels)


/usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
/usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/legacy_tf_layers/core.py:318: UserWarning: `tf.layers.flatten` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Flatten` instead.
  warnings.warn('`tf.layers.flatten` is deprecated and '


In [36]:
!pip uninstall numba
!pip install numba


Found existing installation: numba 0.60.0
Uninstalling numba-0.60.0:
  Would remove:
    /usr/local/bin/numba
    /usr/local/lib/python3.10/dist-packages/numba-0.60.0.dist-info/*
    /usr/local/lib/python3.10/dist-packages/numba/*
Proceed (Y/n)? u
Your response ('u') was not one of the expected responses: y, n, 
Proceed (Y/n)? Y
  Successfully uninstalled numba-0.60.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 31.7 MB/s eta 0:00:00


In [ ]:
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
import numpy as np # Import numpy since it is used in the code

embeddings = [] # Initialize embeddings as a list
labels = []
with tf.Graph().as_default() , tf.compat.v1.Session() as sess :
  vggish_slim.define_vggish_slim(training = False)
  # Assuming 'c_p' is defined somewhere earlier in the user's code
  vggish_slim.load_vggish_slim_checkpoint(sess , c_p)
  features_tensor = sess.graph.get_tensor_by_name(vggish_params.INPUT_TENSOR_NAME)
  embedding_tensor = sess.graph.get_tensor_by_name(vggish_params.OUTPUT_TENSOR_NAME)

  for item in n_d:
    audio_path = item['audio']
    label = item['label']

    # Check if the file exists
    if not tf.io.gfile.exists(audio_path):
      print(f"Warning: File not found: {audio_path}. Skipping.")
      continue

    try:
      examples_batch = vggish_input.wavfile_to_examples(audio_path)
      [embedding] = sess.run([embedding_tensor], feed_dict={features_tensor: examples_batch})
      embeddings.append(embedding) # Append to the embeddings list
      labels.append(label)
    except Exception as e:
      print(f"Error processing {audio_path}: {e}")
      continue # Skip to the next file if an error occurs

# Convert lists to numpy arrays outside the loop
embeddings = np.array(embeddings)
labels = np.array(labels)

# Save embeddings and labels
np.save('embeddings.npy', embeddings)
np.save('labels.npy', labels)

In [ ]:
embeddings[1]

array([[-0.27391323, -0.17884791,  0.12654534, ..., -0.02696085,
         0.07407589, -0.139667  ],
       [-0.20724842, -0.14778522,  0.3562619 , ..., -0.38262555,
         0.05890989,  0.2050567 ],
       [-0.4858509 , -0.62155354,  0.10079029, ..., -0.49898317,
        -0.1113894 , -0.29800814],
       ...,
       [-0.746439  , -0.0092261 ,  0.1312711 , ..., -0.86261296,
         1.0257379 , -0.07771236],
       [-0.55719113, -0.04620832,  0.11102894, ..., -0.80669045,
         0.3084126 , -0.23479113],
       [-0.10625958, -0.15568554,  0.20860991, ..., -0.57000494,
         0.25292945,  0.00102916]], dtype=float32)

In [ ]:
labels = to_categorical(labels , num_classes=10)

In [ ]:
reshaped_embeddings = np.mean(embeddings, axis=1)
reshaped_embeddings.shape

(999, 128)

In [ ]:
embeddings.shape

(999, 31, 128)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense , Dropout , BatchNormalization , InputLayer

In [ ]:
fucking_new_model = Sequential([
    Dense(1024 , activation = 'relu' , input_shape = (128 ,)),
    Dense(512 , activation = 'relu' , input_shape = (128 ,)),
    Dropout(0.2) ,
    Dense(256 , activation = 'relu' , input_shape = (128 ,))
    ,Dropout(0.5),
    Dense(128 , activation = 'relu' , input_shape = (128 ,))
    ,Dropout(0.5)
    ,BatchNormalization()
    ,Dense(256 , activation = 'relu')
    ,Dropout(0.5) ,
    Dense(10 , activation = 'softmax')
])

In [ ]:
fucking_new_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [ ]:
fucking_new_model.fit(reshaped_embeddings , labels , epochs = 1000 , batch_size = 32 , validation_split = 0.25)

Epoch 1/100
12/12 [==============================] - 4s 58ms/step - loss: 2.3041 - accuracy: 0.1883 - val_loss: 2.4654 - val_accuracy: 0.0000e+00
Epoch 2/100
12/12 [==============================] - 0s 27ms/step - loss: 1.6716 - accuracy: 0.3632 - val_loss: 2.5721 - val_accuracy: 0.0000e+00
Epoch 3/100
12/12 [==============================] - 0s 24ms/step - loss: 1.1740 - accuracy: 0.5714 - val_loss: 2.7171 - val_accuracy: 0.0000e+00
Epoch 4/100
12/12 [==============================] - 0s 15ms/step - loss: 0.9362 - accuracy: 0.6862 - val_loss: 2.8827 - val_accuracy: 0.0000e+00
Epoch 5/100
12/12 [==============================] - 0s 25ms/step - loss: 0.7565 - accuracy: 0.7450 - val_loss: 3.1437 - val_accuracy: 0.0000e+00
Epoch 6/100
12/12 [==============================] - 0s 23ms/step - loss: 0.6719 - accuracy: 0.7717 - val_loss: 3.3254 - val_accuracy: 0.0080
Epoch 7/100
12/12 [==============================] - 0s 18ms/step - loss: 0.6080 - accuracy: 0.7997 - val_loss: 3.6095 - val_acc

In [ ]:
# prompt: print the accuracy

# ... (your existing code) ...

# Evaluate the model
loss, accuracy = fucking_new_model.evaluate(reshaped_embeddings, labels, verbose=0)
print('Accuracy: %.2f%%' % (accuracy * 100))


Accuracy: 78.78%


In [ ]:
from tensorflow.keras.layers import Conv2D , MaxPooling2D , Flatten
from tensorflow.keras.regularizers import l2

In [ ]:
nmodel = Sequential()
nmodel.add(InputLayer(input_shape=(128 , )))
nmodel.add(Dense(512, activation='relu', kernel_regularizer=l2(0.01)))
nmodel.add(BatchNormalization())
nmodel.add(Dropout(0.5))
nmodel.add(Dense(256, activation='relu', kernel_regularizer=l2(0.01)))
nmodel.add(BatchNormalization())
nmodel.add(Dropout(0.5))
nmodel.add(Dense(256, activation='relu', kernel_regularizer=l2(0.01)))
nmodel.add(BatchNormalization())
nmodel.add(Dropout(0.5))
nmodel.add(Dense(128, activation='relu', kernel_regularizer=l2(0.01)))
nmodel.add(BatchNormalization())
nmodel.add(Dropout(0.5))
nmodel.add(Dense(64, activation='relu', kernel_regularizer=l2(0.01)))
nmodel.add(BatchNormalization())
nmodel.add(Dropout(0.5))
nmodel.add(Dense(10, activation='softmax'))


In [ ]:
nmodel.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
nmodel.fit(X_train , y_train , epochs = 650 , batch_size = 32 )

Epoch 1/650
25/25 [==============================] - 0s 9ms/step - loss: 0.9568 - accuracy: 0.8335
Epoch 2/650
25/25 [==============================] - 0s 8ms/step - loss: 0.9750 - accuracy: 0.8060
Epoch 3/650
25/25 [==============================] - 0s 9ms/step - loss: 0.9722 - accuracy: 0.8073
Epoch 4/650
25/25 [==============================] - 0s 9ms/step - loss: 0.9534 - accuracy: 0.8110
Epoch 5/650
25/25 [==============================] - 0s 9ms/step - loss: 0.9284 - accuracy: 0.8235
Epoch 6/650
25/25 [==============================] - 0s 8ms/step - loss: 0.9829 - accuracy: 0.8173
Epoch 7/650
25/25 [==============================] - 0s 8ms/step - loss: 1.0534 - accuracy: 0.7972
Epoch 8/650
25/25 [==============================] - 0s 10ms/step - loss: 1.0070 - accuracy: 0.8010
Epoch 9/650
25/25 [==============================] - 0s 9ms/step - loss: 0.9507 - accuracy: 0.8235
Epoch 10/650
25/25 [==============================] - 0s 8ms/step - loss: 0.9608 - accuracy: 0.8323
Epoch 11

In [ ]:
# prompt: print accuracy using test

loss, accuracy = nmodel.evaluate(X_test, y_test, verbose=0)
print('Accuracy: %.2f%%' % (accuracy * 100))


Accuracy: 83.50%


In [ ]:
# prompt: save nmidek into GitHub

# You'll need to set up your GitHub credentials and configure the repository for this to work.
# This is a basic example and may need adjustments based on your specific setup.

# Install necessary libraries
!pip install -q pygithub
import tensorflow as tf
from github import Github

# Replace with your GitHub personal access token
access_token = "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"

# Replace with your GitHub username and repository name
username = "TrishankV"
repo_name = "Music-Genre-Classifier"
nmodel.save('/content/nmodel86.h5')
# Authenticate with GitHub
g = Github(access_token)
repo = g.get_user().get_repo(repo_name)

# Upload the model file
with open('/content/nmodel86.h5', 'rb') as f:
  repo.create_file(
      path="nmodel86.h5",
      message="Added nmodel",
      content=f.read(),
      branch="main"  # Change to your branch if needed
  )

print("Model saved and committed to GitHub!")


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


GithubException: 422 {"message": "Invalid request.\n\n\"sha\" wasn't supplied.", "documentation_url": "https://docs.github.com/rest/repos/contents#create-or-update-file-contents", "status": "422"}

In [ ]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.model_selection import train_test_split, GridSearchCV

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(reshaped_embeddings, labels, test_size=0.2, random_state=42)

# Define the classifiers
rf_clf = RandomForestClassifier()
gb_clf = GradientBoostingClassifier()


In [ ]:
class_indices = np.argmax(labels, axis=1)

# Now class_indices will be of shape (532,)
print(class_indices.shape)

(999,)


In [ ]:
X , xt , y  , yt = train_test_split(reshaped_embeddings , class_indices , test_size = 0.2 , random_state = 42)

In [ ]:
import time

In [ ]:
rf_param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 20, 30],
    'min_samples_split': [2, 5, 10]
}

gb_param_grid = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 5, 7]
}

# Perform GridSearchCV for each classifier
rf_grid_search = GridSearchCV(rf_clf, rf_param_grid, cv=3, n_jobs=1, verbose=2)
gb_grid_search = GridSearchCV(gb_clf, gb_param_grid, cv=3, n_jobs=1, verbose=2)
# Measure the time taken for the grid search
start_time = time.time()
# Fit the models
rf_grid_search.fit(X, y)
gb_grid_search.fit(X, y)

Fitting 3 folds for each of 27 candidates, totalling 81 fits
[CV] END max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.8s
[CV] END max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.8s
[CV] END max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.8s
[CV] END max_depth=10, min_samples_split=2, n_estimators=200; total time=   1.6s
[CV] END max_depth=10, min_samples_split=2, n_estimators=200; total time=   1.6s
[CV] END max_depth=10, min_samples_split=2, n_estimators=200; total time=   2.5s
[CV] END max_depth=10, min_samples_split=2, n_estimators=300; total time=   2.9s
[CV] END max_depth=10, min_samples_split=2, n_estimators=300; total time=   2.5s
[CV] END max_depth=10, min_samples_split=2, n_estimators=300; total time=   2.6s
[CV] END max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.7s
[CV] END max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.6s
[CV] END max_depth=10, min_samples_split=5, n_es

KeyboardInterrupt: 

In [ ]:
rf_predictions = best_rf.predict(X_test)
gb_predictions = best_gb.predict(X_test)

rf_accuracy = accuracy_score(y_test, rf_predictions)
gb_accuracy = accuracy_score(y_test, gb_predictions)

print(f'Random Forest Accuracy: {rf_accuracy}')
print(f'Gradient Boosting Accuracy: {gb_accuracy}')

# Combine predictions using majority voting (simple ensemble method)
final_predictions = np.round((rf_predictions + gb_predictions) / 2).astype(int)
final_accuracy = accuracy_score(y_test, final_predictions)

print(f'Ensemble Model Accuracy: {final_accuracy}')

In [ ]:
!pip install openl3
!pip install soundfile


  Preparing metadata (setup.py) ... done
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 323.4/323.4 kB 13.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for openl3: filename=openl3-0.4.2-py2.py3-none-any.whl size=249327034 sha256=16a9ba6be54e3e7fac366e4b4489e7394a9100d0f2c8756f7b671d9a6dbe3bad
  Stored in directory: /root/.cache/pip/wheels/d0/4d/0a/e57b1dc8ead91b3c5709d9de4f02d1cdd3a91f609a8f1c1062
  Created wheel for kapre: filename=kapre-0.3.7-py3-none-any.whl size=29603 sha256=3b37d98443b08465b1d2b07d16775a70e0884cbe88f7e1862c944bdcabb65e03
  Stored in directory: /root/.cache/pip/wheels/3e/54/f9/37e9f36590a5431dc207f7dc0eb2e607ff8958d5728e45ef58
  Created wheel for resampy: filename=resampy-0.2.2-py3-none-any.whl size=320708 sha256=618f907c9e35e0d760f9b50742789a0b22e2be18fb7a6812f6761b26a97c3882
  Stored in directory: /roo

In [ ]:
import openl3
import numpy as np
import soundfile as sf

# Assuming `n_d` is your list of dictionaries with 'audio' and 'label'
# Example: n_d = [{'audio': '/path/to/audio.wav', 'label': 0}, ...]

embeddings = []  # Initialize embeddings as a list
labels = []

for item in n_d:
    audio_path = item['audio']
    label = item['label']

    # Load and preprocess the audio file
    audio, sr = sf.read(audio_path)

    # Ensure audio is mono and has correct sample rate
    if len(audio.shape) > 1:
        audio = audio[:, 0]  # Take the first channel if stereo
    if sr != 16000:
        raise ValueError("Sample rate should be 16000 Hz")

    # Extract embeddings using OpenL3
    embedding, _ = openl3.get_audio_embedding(audio, sr, embedding_model='mel256')

    # Append the mean of the embeddings to the list
    embeddings.append(np.mean(embedding, axis=0))
    labels.append(label)

# Convert lists to numpy arrays outside the loop
embeddings = np.array(embeddings)
labels = np.array(labels)

# Save embeddings and labels
np.save('embeddings.npy', embeddings)
np.save('labels.npy', labels)

print(f"Embeddings shape: {embeddings.shape}")
print(f"Labels shape: {labels.shape}")


NameError: name 'n_d' is not defined

In [21]:
# prompt: I have nmodel86.hf in in/content/ now I want to classify one file to see if ti works using VGGISH

import tensorflow as tf
import vggish_input
import vggish_params
import vggish_slim
import numpy as np
from tensorflow.keras.models import load_model

# Load the saved model
model = load_model('/content/nmodel86.h5')

# Define the path to your audio file
audio_file = '/content/Data/genres_original/blues/blues.00002.wav'  # Replace with your actual file path

# Load the VGGish model and extract embeddings
with tf.Graph().as_default(), tf.compat.v1.Session() as sess:
  vggish_slim.define_vggish_slim(training=False)
  vggish_slim.load_vggish_slim_checkpoint(sess, '/content/vggish_model.ckpt')
  features_tensor = sess.graph.get_tensor_by_name(vggish_params.INPUT_TENSOR_NAME)
  embedding_tensor = sess.graph.get_tensor_by_name(vggish_params.OUTPUT_TENSOR_NAME)

  examples_batch = vggish_input.wavfile_to_examples(audio_file)
  [embedding] = sess.run([embedding_tensor], feed_dict={features_tensor: examples_batch})

# Preprocess the embedding
reshaped_embedding = np.mean(embedding, axis=0)  # Average over time frames

# Make a prediction with the loaded model
prediction = model.predict(np.expand_dims(reshaped_embedding, axis=0))

# Get the predicted class index
predicted_class = np.argmax(prediction)

# Print the predicted class (you'll need to map this to your actual genre labels)
print(f"Predicted class index: {predicted_class}")

# Example mapping of class index to genre label (replace with your actual mapping)
genre_labels = ['blues', 'classical', 'country', 'disco', 'hiphop', 'jazz', 'metal', 'pop', 'reggae', 'rock']
predicted_genre = genre_labels[predicted_class]
print(f"Predicted genre: {predicted_genre}")


/usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
/usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/legacy_tf_layers/core.py:318: UserWarning: `tf.layers.flatten` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Flatten` instead.
  warnings.warn('`tf.layers.flatten` is deprecated and '


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 886ms/step
Predicted class index: 0
Predicted genre: blues


In [28]:
# prompt: Make a streamlit app to do the same , also convert the first 30 seconds of MP3 to wav before doing it and save the file as app.py

import streamlit as st
import librosa
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
import vggish_input
import vggish_params
import vggish_slim
import soundfile as sf
import pydub
from pydub import AudioSegment

# Load the trained model
model = load_model('/content/nmodel86.h5')  # Replace with the actual path to your model

# Define the genre labels
genre_labels = ['blues', 'classical', 'country', 'disco', 'hiphop', 'jazz', 'metal', 'pop', 'reggae', 'rock']

# Function to extract VGGish embeddings
def extract_embeddings(audio_file):
  with tf.Graph().as_default(), tf.compat.v1.Session() as sess:
    vggish_slim.define_vggish_slim(training=False)
    vggish_slim.load_vggish_slim_checkpoint(sess, '/content/vggish_model.ckpt')  # Replace with the actual path to the VGGish checkpoint
    features_tensor = sess.graph.get_tensor_by_name(vggish_params.INPUT_TENSOR_NAME)
    embedding_tensor = sess.graph.get_tensor_by_name(vggish_params.OUTPUT_TENSOR_NAME)

    examples_batch = vggish_input.wavfile_to_examples(audio_file)
    [embedding] = sess.run([embedding_tensor], feed_dict={features_tensor: examples_batch})

  return np.mean(embedding, axis=0)

# Function to predict the genre
def predict_genre(audio_file):
  embedding = extract_embeddings(audio_file)
  prediction = model.predict(np.expand_dims(embedding, axis=0))
  predicted_class = np.argmax(prediction)
  return genre_labels[predicted_class]

# Streamlit app
def main():
  st.title("Music Genre Classifier")
  st.write("Upload an audio file (MP3 or WAV) to classify its genre.")

  uploaded_file = st.file_uploader("Choose an audio file", type=["mp3", "wav"])

  if uploaded_file is not None:
    # Convert MP3 to WAV if necessary
    if uploaded_file.name.endswith(".mp3"):
      audio = AudioSegment.from_mp3(uploaded_file)
      # Extract first 30 seconds
      audio = audio[:30000]  # 30 seconds in milliseconds
      wav_file = "temp.wav"
      audio.export(wav_file, format="wav")
      audio_path = wav_file
    else:
      audio_path = "temp.wav"  # Save the uploaded WAV file temporarily
      with open(audio_path, "wb") as f:
        f.write(uploaded_file.getbuffer())

    # Predict the genre
    try:
      predicted_genre = predict_genre(audio_path)
      st.write(f"Predicted Genre: **{predicted_genre}**")
    except Exception as e:
      st.error(f"Error during prediction: {e}")

if __name__ == "__main__":
  main()


In [36]:

# Run the Streamlit app in the background
!streamlit run app.py &>/dev/null&

# Expose the Streamlit app using localtunnel
!npx localtunnel --port 8501


your url is: https://six-spoons-reply.loca.lt
^C


In [27]:
!pip install pydub # Install the openl3 library

In [35]:
!curl https://loca.lt/mytunnelpassword

34.125.155.85

In [ ]:
# prompt: now please upload all of this image in docker

# This code snippet is not applicable for Docker image creation.
# It provides the Python code for the music genre classifier and Streamlit app.

# To create a Docker image, you'll need a Dockerfile with instructions for setting up the environment and running the app.

# Here's a basic Dockerfile structure you can adapt:

# Dockerfile
FROM python:3.9-slim-buster

# Set working directory
WORKDIR /app

# Copy requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy the app code
COPY . .

# Expose the port for Streamlit
EXPOSE 8501

# Start the Streamlit app
CMD ["streamlit", "run", "app.py"]

# To build the image:
# docker build -t music-genre-classifier .

# To run the container:
# docker run -p 8501:8501 music-genre-classifier

# Remember to replace "music-genre-classifier" with your desired image name.
# Also, make sure to adjust the Dockerfile based on your specific requirements and dependencies.


In [38]:
# prompt: upload all of the above files in GitHub
import tensorflow as tf
from github import Github
# Install necessary libraries
!pip install -q pygithub

# Replace with your GitHub personal access token
access_token = "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"

# Replace with your GitHub username and repository name
username = "TrishankV"
repo_name = "Music-Genre-Classifier"

# Authenticate with GitHub
g = Github(access_token)
repo = g.get_user().get_repo(repo_name)

# Upload the model file
with open('/content/nmodel86.h5', 'rb') as f:
  repo.create_file(
      path="nmodel86.h5",
      message="Added nmodel",
      content=f.read(),
      branch="main"  # Change to your branch if needed
  )

print("Model saved and committed to GitHub!")


GithubException: 422 {"message": "Invalid request.\n\n\"sha\" wasn't supplied.", "documentation_url": "https://docs.github.com/rest/repos/contents#create-or-update-file-contents", "status": "422"}

In [39]:
from google.colab import auth
auth.authenticate_user()

In [42]:
!docker build -t music-genre-classifier .

/bin/bash: line 1: docker: command not found


In [43]:
!gcloud builds submit --config cloudbuild.yaml .

ERROR: (gcloud.builds.submit) The required property [project] is not currently set.
It can be set on a per-command basis by re-running your command with the [--project] flag.

You may set it for your current workspace by running:

  $ gcloud config set project VALUE

or it can be set temporarily by the environment variable [CLOUDSDK_CORE_PROJECT]


In [51]:
!gcloud builds submit --config cloudbuild.yaml --project static-mediator-431214-f6

ERROR: (gcloud.builds.submit) The user is forbidden from accessing the bucket [static-mediator-431214-f6_cloudbuild]. Please check your organization's policy or if the user has the "serviceusage.services.use" permission. Giving the user Owner, Editor, or Viewer roles may also fix this issue. Alternatively, use the --no-source option and access your source code via a different method.


In [52]:
!gcloud builds submit --config cloudbuild.yaml --no-source --project static-mediator-431214-f6

API [cloudbuild.googleapis.com] not enabled on project [810456310371]. Would you
 like to enable and retry (this will take a few minutes)? (y/N)?  

Command killed by keyboard interrupt

^C


In [53]:
!pip install pyinstaller

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 685.0/685.0 kB 14.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.3/341.3 kB 14.7 MB/s eta 0:00:00


In [49]:
import os
os.environ['CLOUDSDK_CORE_PROJECT'] = 'static-mediator-431214-f6.'

In [ ]:
!pyinstaller --onefile app.py

630 INFO: PyInstaller: 6.9.0, contrib hooks: 2024.7
630 INFO: Python: 3.10.12
632 INFO: Platform: Linux-6.1.85+-x86_64-with-glibc2.35
632 INFO: Python environment: /usr
632 INFO: wrote /content/app.spec
636 INFO: Module search paths (PYTHONPATH):
['/env/python',
 '/usr/lib/python310.zip',
 '/usr/lib/python3.10',
 '/usr/lib/python3.10/lib-dynload',
 '/usr/local/lib/python3.10/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/local/lib/python3.10/dist-packages/setuptools/_vendor',
 '/content']
pygame 2.6.0 (SDL 2.28.4, Python 3.10.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
1746 INFO: checking Analysis
1746 INFO: Building Analysis because Analysis-00.toc is non existent
1746 INFO: Running Analysis Analysis-00.toc
1746 INFO: Target bytecode optimization level: 0
1746 INFO: Initializing module dependency graph...
1747 INFO: Caching module graph hooks...
1761 INFO: Analyzing base_library.zip ...
3678 INFO: Loading module hook 'hook-heapq.py' from '/us

In [47]:
!gcloud config set project static-mediator-431214-f6

Updated property [core/project].


In [57]:
!"/usr/bin/python3" -m pip uninstall pathlib

Found existing installation: pathlib 1.0.1
Uninstalling pathlib-1.0.1:
  Would remove:
    /usr/local/lib/python3.10/dist-packages/pathlib-1.0.1.dist-info/*
    /usr/local/lib/python3.10/dist-packages/pathlib.py
Proceed (Y/n)? Y
  Successfully uninstalled pathlib-1.0.1
